[tools]
lefthook = "latest"
"npm:genkit-cli" = "latest"

[env]
_.file = ".env.local"

[tasks]
start.run = "genkit start -- go run ."
kill-research-ports.run = "lsof -i :4033 -i :4000 -i :3400 -nP | grep research | awk '{print $2}' | sort | uniq | xargs -r kill -9"
register-mcp.run = "go run script/register-local-mcp/main.go"
fmt.run = "go fmt ./..."
dev.run = "mise watch start -r"
