[tools]
"npm:genkit-cli" = "latest"

[env]
GEMINI_API_KEY = "AIzaSyBTEgK53iynAQwvdm48YRxZsmzYBFqlDUc"

[tasks.dev]
run = "genkit start -- go run ."

[tasks.kill]
run = "lsof -i -nP | grep (pgrep -f research) | awk '{print $2}' | sort | uniq | xargs kill"

[tasks.kill2]
run = "pkill -f research || true; lsof -i -nP | grep LISTEN | awk '{print $2}' | sort | uniq | xargs -r kill -9"
