[tools]
"npm:genkit-cli" = "latest"

[env]
_.file = ".env.local"

[tasks.dev]
run = "genkit start -- go run ."

[tasks.kill-research-ports]
run = "lsof -i :4033 -i :4000 -i :3400 -nP | grep research | awk '{print $2}' | sort | uniq | xargs -r kill -9"

[tasks.register-mcp]
run = "go run script/register-local-mcp/main.go"
